const countries = [
  { "label": "No Country", "value": "" },
  { "label": "Andorra (AD)", "value": "AD" },
  { "label": "United Arab Emirates (AE)", "value": "AE" },
  { "label": "Afghanistan (AF)", "value": "AF" },
  { "label": "Antigua and Barbuda (AG)", "value": "AG" },
  { "label": "Anguilla (AI)", "value": "AI" },
  { "label": "Albania (AL)", "value": "AL" },
  { "label": "Armenia (AM)", "value": "AM" },
  { "label": "Angola (AO)", "value": "AO" },
  { "label": "Argentina (AR)", "value": "AR" },
  { "label": "American Samoa (AS)", "value": "AS" },
  { "label": "Austria (AT)", "value": "AT" },
  { "label": "Australia (AU)", "value": "AU" },
  { "label": "Aruba (AW)", "value": "AW" },
  { "label": "Åland Islands (AX)", "value": "AX" },
  { "label": "Azerbaijan (AZ)", "value": "AZ" },
  { "label": "Bosnia and Herzegovina (BA)", "value": "BA" },
  { "label": "Barbados (BB)", "value": "BB" },
  { "label": "Bangladesh (BD)", "value": "BD" },
  { "label": "Belgium (BE)", "value": "BE" },
  { "label": "Burkina Faso (BF)", "value": "BF" },
  { "label": "Bulgaria (BG)", "value": "BG" },
  { "label": "Bahrain (BH)", "value": "BH" },
  { "label": "Burundi (BI)", "value": "BI" },
  { "label": "Benin (BJ)", "value": "BJ" },
  { "label": "Saint Barthélemy (BL)", "value": "BL" },
  { "label": "Bermuda (BM)", "value": "BM" },
  { "label": "Brunei Darussalam (BN)", "value": "BN" },
  { "label": "Bolivia (Plurinational State of) (BO)", "value": "BO" },
  { "label": "Brazil (BR)", "value": "BR" },
  { "label": "Bahamas (BS)", "value": "BS" },
  { "label": "Bhutan (BT)", "value": "BT" },
  { "label": "Bouvet Island (BV)", "value": "BV" },
  { "label": "Botswana (BW)", "value": "BW" },
  { "label": "Belarus (BY)", "value": "BY" },
  { "label": "Belize (BZ)", "value": "BZ" },
  { "label": "Canada (CA)", "value": "CA" },
  { "label": "Cocos (Keeling) Islands (CC)", "value": "CC" },
  { "label": "Congo (the Democratic Republic of the) (CD)", "value": "CD" },
  { "label": "Central African Republic (CF)", "value": "CF" },
  { "label": "Congo (CG)", "value": "CG" },
  { "label": "Switzerland (CH)", "value": "CH" },
  { "label": "Côte d'Ivoire (CI)", "value": "CI" },
  { "label": "Cook Islands (CK)", "value": "CK" },
  { "label": "Chile (CL)", "value": "CL" },
  { "label": "Cameroon (CM)", "value": "CM" },
  { "label": "China (CN)", "value": "CN" },
  { "label": "Colombia (CO)", "value": "CO" },
  { "label": "Costa Rica (CR)", "value": "CR" },
  { "label": "Cuba (CU)", "value": "CU" },
  { "label": "Cabo Verde (CV)", "value": "CV" },
  { "label": "Curaçao (CW)", "value": "CW" },
  { "label": "Christmas Island (CX)", "value": "CX" },
  { "label": "Cyprus (CY)", "value": "CY" },
  { "label": "Czechia (CZ)", "value": "CZ" },
  { "label": "Germany (DE)", "value": "DE" },
  { "label": "Djibouti (DJ)", "value": "DJ" },
  { "label": "Denmark (DK)", "value": "DK" },
  { "label": "Dominica (DM)", "value": "DM" },
  { "label": "Dominican Republic (DO)", "value": "DO" },
  { "label": "Algeria (DZ)", "value": "DZ" },
  { "label": "Ecuador (EC)", "value": "EC" },
  { "label": "Estonia (EE)", "value": "EE" },
  { "label": "Egypt (EG)", "value": "EG" },
  { "label": "Eritrea (ER)", "value": "ER" },
  { "label": "Spain (ES)", "value": "ES" },
  { "label": "Ethiopia (ET)", "value": "ET" },
  { "label": "European Union (EU)", "value": "EU" },
  { "label": "Finland (FI)", "value": "FI" },
  { "label": "Fiji (FJ)", "value": "FJ" },
  { "label": "Falkland Islands (Malvinas) (FK)", "value": "FK" },
  { "label": "Micronesia (Federated States of) (FM)", "value": "FM" },
  { "label": "Faroe Islands (FO)", "value": "FO" },
  { "label": "France (FR)", "value": "FR" },
  { "label": "Gabon (GA)", "value": "GA" },
  { "label": "United Kingdom of Great Britain and Northern Ireland (GB)", "value": "GB" },
  { "label": "England (GB-ENG)", "value": "GB-ENG" },
  { "label": "Northern Ireland (GB-NIR)", "value": "GB-NIR" },
  { "label": "Scotland (GB-SCT)", "value": "GB-SCT" },
  { "label": "Wales (GB-WLS)", "value": "GB-WLS" },
  // { "label": "Shetland Islands (GB-ZET)", "value": "GB-ZET" },
  { "label": "Grenada (GD)", "value": "GD" },
  { "label": "Georgia (GE)", "value": "GE" },
  { "label": "French Guiana (GF)", "value": "GF" },
  { "label": "Guernsey (GG)", "value": "GG" },
  { "label": "Ghana (GH)", "value": "GH" },
  { "label": "Gibraltar (GI)", "value": "GI" },
  { "label": "Greenland (GL)", "value": "GL" },
  { "label": "Gambia (GM)", "value": "GM" },
  { "label": "Guinea (GN)", "value": "GN" },
  { "label": "Guadeloupe (GP)", "value": "GP" },
  { "label": "Equatorial Guinea (GQ)", "value": "GQ" },
  { "label": "Greece (GR)", "value": "GR" },
  { "label": "South Georgia and the South Sandwich Islands (GS)", "value": "GS" },
  { "label": "Guatemala (GT)", "value": "GT" },
  { "label": "Guam (GU)", "value": "GU" },
  { "label": "Guinea-Bissau (GW)", "value": "GW" },
  { "label": "Guyana (GY)", "value": "GY" },
  { "label": "Hong Kong (HK)", "value": "HK" },
  { "label": "Heard Island and McDonald Islands (HM)", "value": "HM" },
  { "label": "Honduras (HN)", "value": "HN" },
  { "label": "Croatia (HR)", "value": "HR" },
  { "label": "Haiti (HT)", "value": "HT" },
  { "label": "Hungary (HU)", "value": "HU" },
  { "label": "Indonesia (ID)", "value": "ID" },
  { "label": "Ireland (IE)", "value": "IE" },
  { "label": "Israel (IL)", "value": "IL" },
  { "label": "Isle of Man (IM)", "value": "IM" },
  { "label": "India (IN)", "value": "IN" },
  { "label": "British Indian Ocean Territory (IO)", "value": "IO" },
  { "label": "Iraq (IQ)", "value": "IQ" },
  { "label": "Iran (Islamic Republic of) (IR)", "value": "IR" },
  { "label": "Iceland (IS)", "value": "IS" },
  { "label": "Italy (IT)", "value": "IT" },
  { "label": "Jersey (JE)", "value": "JE" },
  { "label": "Jamaica (JM)", "value": "JM" },
  { "label": "Jordan (JO)", "value": "JO" },
  { "label": "Japan (JP)", "value": "JP" },
  { "label": "Kenya (KE)", "value": "KE" },
  { "label": "Kyrgyzstan (KG)", "value": "KG" },
  { "label": "Cambodia (KH)", "value": "KH" },
  { "label": "Kiribati (KI)", "value": "KI" },
  { "label": "Comoros (KM)", "value": "KM" },
  { "label": "Saint Kitts and Nevis (KN)", "value": "KN" },
  { "label": "Korea (the Democratic People's Republic of) (KP)", "value": "KP" },
  { "label": "Korea (the Republic of) (KR)", "value": "KR" },
  { "label": "Kuwait (KW)", "value": "KW" },
  { "label": "Cayman Islands (KY)", "value": "KY" },
  { "label": "Kazakhstan (KZ)", "value": "KZ" },
  { "label": "Lao People's Democratic Republic (LA)", "value": "LA" },
  { "label": "Lebanon (LB)", "value": "LB" },
  { "label": "Saint Lucia (LC)", "value": "LC" },
  { "label": "LGBT (LGBT)", "value": "LGBT" },
  { "label": "Liechtenstein (LI)", "value": "LI" },
  { "label": "Sri Lanka (LK)", "value": "LK" },
  { "label": "Liberia (LR)", "value": "LR" },
  { "label": "Lesotho (LS)", "value": "LS" },
  { "label": "Lithuania (LT)", "value": "LT" },
  { "label": "Luxembourg (LU)", "value": "LU" },
  { "label": "Latvia (LV)", "value": "LV" },
  { "label": "Libya (LY)", "value": "LY" },
  { "label": "Morocco (MA)", "value": "MA" },
  { "label": "Monaco (MC)", "value": "MC" },
  { "label": "Moldova (the Republic of) (MD)", "value": "MD" },
  { "label": "Montenegro (ME)", "value": "ME" },
  { "label": "Saint Martin (French part) (MF)", "value": "MF" },
  { "label": "Madagascar (MG)", "value": "MG" },
  { "label": "Marshall Islands (MH)", "value": "MH" },
  { "label": "North Macedonia (MK)", "value": "MK" },
  { "label": "Mali (ML)", "value": "ML" },
  { "label": "Myanmar (MM)", "value": "MM" },
  { "label": "Mongolia (MN)", "value": "MN" },
  { "label": "Macao (MO)", "value": "MO" },
  { "label": "Northern Mariana Islands (MP)", "value": "MP" },
  { "label": "Martinique (MQ)", "value": "MQ" },
  { "label": "Mauritania (MR)", "value": "MR" },
  { "label": "Montserrat (MS)", "value": "MS" },
  { "label": "Malta (MT)", "value": "MT" },
  { "label": "Mauritius (MU)", "value": "MU" },
  { "label": "Maldives (MV)", "value": "MV" },
  { "label": "Malawi (MW)", "value": "MW" },
  { "label": "Mexico (MX)", "value": "MX" },
  { "label": "Malaysia (MY)", "value": "MY" },
  { "label": "Mozambique (MZ)", "value": "MZ" },
  { "label": "Namibia (NA)", "value": "NA" },
  { "label": "New Caledonia (NC)", "value": "NC" },
  { "label": "Niger (NE)", "value": "NE" },
  { "label": "Norfolk Island (NF)", "value": "NF" },
  { "label": "Nigeria (NG)", "value": "NG" },
  { "label": "Nicaragua (NI)", "value": "NI" },
  { "label": "Netherlands (NL)", "value": "NL" },
  { "label": "Norway (NO)", "value": "NO" },
  { "label": "Nepal (NP)", "value": "NP" },
  { "label": "Nauru (NR)", "value": "NR" },
  { "label": "Niue (NU)", "value": "NU" },
  { "label": "New Zealand (NZ)", "value": "NZ" },
  { "label": "Oman (OM)", "value": "OM" },
  { "label": "Panama (PA)", "value": "PA" },
  { "label": "Peru (PE)", "value": "PE" },
  { "label": "French Polynesia (PF)", "value": "PF" },
  { "label": "Papua New Guinea (PG)", "value": "PG" },
  { "label": "Philippines (PH)", "value": "PH" },
  { "label": "Pakistan (PK)", "value": "PK" },
  { "label": "Poland (PL)", "value": "PL" },
  { "label": "Saint Pierre and Miquelon (PM)", "value": "PM" },
  { "label": "Pitcairn (PN)", "value": "PN" },
  { "label": "Puerto Rico (PR)", "value": "PR" },
  { "label": "Palestine, State of (PS)", "value": "PS" },
  { "label": "Portugal (PT)", "value": "PT" },
  { "label": "Palau (PW)", "value": "PW" },
  { "label": "Paraguay (PY)", "value": "PY" },
  { "label": "Qatar (QA)", "value": "QA" },
  { "label": "Réunion (RE)", "value": "RE" },
  { "label": "Romania (RO)", "value": "RO" },
  { "label": "Serbia (RS)", "value": "RS" },
  { "label": "Russian Federation (RU)", "value": "RU" },
  { "label": "Rwanda (RW)", "value": "RW" },
  { "label": "Saudi Arabia (SA)", "value": "SA" },
  { "label": "Solomon Islands (SB)", "value": "SB" },
  { "label": "Seychelles (SC)", "value": "SC" },
  { "label": "Sudan (SD)", "value": "SD" },
  { "label": "Sweden (SE)", "value": "SE" },
  { "label": "Singapore (SG)", "value": "SG" },
  { "label": "Saint Helena, Ascension and Tristan da Cunha (SH)", "value": "SH" },
  { "label": "Slovenia (SI)", "value": "SI" },
  { "label": "Svalbard and Jan Mayen (SJ)", "value": "SJ" },
  { "label": "Slovakia (SK)", "value": "SK" },
  { "label": "Sierra Leone (SL)", "value": "SL" },
  { "label": "San Marino (SM)", "value": "SM" },
  { "label": "Senegal (SN)", "value": "SN" },
  { "label": "Somalia (SO)", "value": "SO" },
  { "label": "Suriname (SR)", "value": "SR" },
  { "label": "South Sudan (SS)", "value": "SS" },
  { "label": "Sao Tome and Principe (ST)", "value": "ST" },
  { "label": "El Salvador (SV)", "value": "SV" },
  { "label": "Sint Maarten (Dutch part) (SX)", "value": "SX" },
  { "label": "Syrian Arab Republic (SY)", "value": "SY" },
  { "label": "Eswatini (SZ)", "value": "SZ" },
  { "label": "Turks and Caicos Islands (TC)", "value": "TC" },
  { "label": "Chad (TD)", "value": "TD" },
  { "label": "French Southern Territories (TF)", "value": "TF" },
  { "label": "Togo (TG)", "value": "TG" },
  { "label": "Thailand (TH)", "value": "TH" },
  { "label": "Tajikistan (TJ)", "value": "TJ" },
  { "label": "Tokelau (TK)", "value": "TK" },
  { "label": "Timor-Leste (TL)", "value": "TL" },
  { "label": "Turkmenistan (TM)", "value": "TM" },
  { "label": "Tunisia (TN)", "value": "TN" },
  { "label": "Tonga (TO)", "value": "TO" },
  { "label": "Turkey (TR)", "value": "TR" },
  { "label": "Trinidad and Tobago (TT)", "value": "TT" },
  { "label": "Tuvalu (TV)", "value": "TV" },
  { "label": "Taiwan (Province of China) (TW)", "value": "TW" },
  { "label": "Tanzania, United Republic of (TZ)", "value": "TZ" },
  { "label": "Ukraine (UA)", "value": "UA" },
  { "label": "Uganda (UG)", "value": "UG" },
  // { "label": "United States Minor Outlying Islands (UM)", "value": "UM" },
  { "label": "United States of America (US)", "value": "US" },
  // { "label": "United States California (US-CA)", "value": "US-CA" },
  { "label": "Uruguay (UY)", "value": "UY" },
  { "label": "Uzbekistan (UZ)", "value": "UZ" },
  { "label": "Holy See (VA)", "value": "VA" },
  { "label": "Saint Vincent and the Grenadines (VC)", "value": "VC" },
  { "label": "Venezuela (Bolivarian Republic of) (VE)", "value": "VE" },
  { "label": "Virgin Islands (British) (VG)", "value": "VG" },
  { "label": "Virgin Islands (U.S.) (VI)", "value": "VI" },
  { "label": "Viet Nam (VN)", "value": "VN" },
  { "label": "Vanuatu (VU)", "value": "VU" },
  { "label": "Wallis and Futuna (WF)", "value": "WF" },
  { "label": "Samoa (WS)", "value": "WS" },
  { "label": "Kosovo (XK)", "value": "XK" },
  { "label": "Blank (XX)", "value": "XX" },
  { "label": "Yemen (YE)", "value": "YE" },
  { "label": "Mayotte (YT)", "value": "YT" },
  { "label": "South Africa (ZA)", "value": "ZA" },
  { "label": "Zambia (ZM)", "value": "ZM" },
  { "label": "Zimbabwe (ZW)", "value": "ZW" }
];

export { countries };
